[project]
name = "googledrive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi>=0.121.1",
    "jwt>=1.4.0",
    "prisma>=0.15.0",
    "uuid>=1.30",
]
